# -*- coding: utf-8 -*-
"""Machine learning Session.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTkqKm5Q1x23w-gRFk2YjjyXoM63TfYU
"""

pip install datasets pandas

from datasets import load_dataset
import pandas as pd

# Load the specific dataset
dataset = load_dataset(
    "FeatEng/Data",
    "arashnic__taxi-pricing-with-mobility-analytics"
)

# Convert train and test splits to pandas
train_df = dataset["train"].to_pandas()
test_df = dataset["test"].to_pandas()

# Save as CSV
train_df.to_csv("zipride_train.csv", index=False)
test_df.to_csv("zipride_test.csv", index=False)

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

print("\nTrain columns:")
print(train_df.columns.tolist())

import pandas as pd

df = pd.read_csv("zipride_train.csv")

df.shape

df.columns

df.info()

df.isnull().sum()

df.duplicated().sum()

df.describe()

"""### **EDA Process**"""

# ============================================================
# ZIPRIDE - EXPLORATORY DATA ANALYSIS (EDA)
# ============================================================

# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv("/content/zipride_train.csv")


# ============================================================
# 3. BASIC DATASET INFORMATION
# ============================================================

print("=" * 60)
print("ZIPRIDE DATASET - BASIC INFORMATION")
print("=" * 60)

print("\nDataset Shape")
print("Rows    :", df.shape[0])
print("Columns :", df.shape[1])

print("\nColumn Information")
df.info()


# ============================================================
# 4. DATA QUALITY CHECK
# ============================================================

print("\n" + "=" * 60)
print("DATA QUALITY CHECK")
print("=" * 60)


# ------------------------------------------------------------
# 4.1 Missing / Null Values
# ------------------------------------------------------------

missing_count = df.isnull().sum()

missing_percentage = (
    df.isnull().mean() * 100
)

missing_summary = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percentage": missing_percentage
})

missing_summary = missing_summary[
    missing_summary["Missing Count"] > 0
].sort_values(
    by="Missing Count",
    ascending=False
)

print("\nMissing / Null Values:")
print(missing_summary)

print("\nTotal Missing / Null Values:",
      df.isnull().sum().sum())


# ------------------------------------------------------------
# 4.2 Duplicate Rows
# ------------------------------------------------------------

duplicate_count = df.duplicated().sum()

print("\nDuplicate Rows:",
      duplicate_count)


# ------------------------------------------------------------
# 4.3 Completely Empty Rows
# ------------------------------------------------------------

empty_rows = df.isnull().all(axis=1).sum()

print("Completely Empty Rows:",
      empty_rows)


# ============================================================
# 5. MISSING VALUE VISUALIZATION
# ============================================================

# ------------------------------------------------------------
# 5.1 Missing Values - Bar Chart
# ------------------------------------------------------------

missing_plot = df.isnull().sum()

missing_plot = missing_plot[
    missing_plot > 0
].sort_values(
    ascending=False
)

plt.figure(figsize=(10, 5))

plt.bar(
    missing_plot.index,
    missing_plot.values
)

plt.title("Missing Values by Column")
plt.xlabel("Columns")
plt.ylabel("Number of Missing Values")

plt.xticks(
    rotation=45,
    ha="right"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 5.2 Missing Percentage - Horizontal Bar Chart
# ------------------------------------------------------------

missing_percent_plot = (
    df.isnull().mean() * 100
)

missing_percent_plot = missing_percent_plot[
    missing_percent_plot > 0
].sort_values()

plt.figure(figsize=(9, 5))

plt.barh(
    missing_percent_plot.index,
    missing_percent_plot.values
)

plt.title("Missing Value Percentage")
plt.xlabel("Missing Percentage (%)")
plt.ylabel("Columns")

plt.tight_layout()
plt.show()


# ============================================================
# 6. UNIVARIATE ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 6.1 Surge Pricing Category - Pie Chart
# ------------------------------------------------------------

target_counts = (
    df["__FeatEng_target__"]
    .value_counts()
    .sort_index()
)

plt.figure(figsize=(7, 7))

plt.pie(
    target_counts.values,
    labels=[
        f"Category {x}"
        for x in target_counts.index
    ],
    autopct="%1.1f%%",
    startangle=90
)

plt.title(
    "Surge Pricing Category Distribution"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 6.2 Trip Distance - Histogram
# ------------------------------------------------------------

plt.figure(figsize=(9, 5))

plt.hist(
    df["Trip_Distance"].dropna(),
    bins=30
)

plt.title("Trip Distance Distribution")
plt.xlabel("Trip Distance")
plt.ylabel("Number of Trips")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 6.3 Customer Rating - Box Plot
# ------------------------------------------------------------

plt.figure(figsize=(8, 5))

plt.boxplot(
    df["Customer_Rating"].dropna(),
    vert=False
)

plt.title("Customer Rating Distribution")
plt.xlabel("Customer Rating")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 6.4 Cancellation - Violin Plot
# ------------------------------------------------------------

cancellation_data = (
    df["Cancellation_Last_1Month"]
    .dropna()
)

plt.figure(figsize=(8, 5))

plt.violinplot(
    cancellation_data,
    vert=False,
    showmeans=True
)

plt.title("Cancellation Distribution")
plt.xlabel(
    "Cancellations in Last 1 Month"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 6.5 Cab Type - Donut Chart
# ------------------------------------------------------------

cab_counts = (
    df["Type_of_Cab"]
    .value_counts(dropna=False)
)

cab_labels = [
    "Unknown" if pd.isna(x) else str(x)
    for x in cab_counts.index
]

plt.figure(figsize=(7, 7))

plt.pie(
    cab_counts.values,
    labels=cab_labels,
    autopct="%1.1f%%",
    startangle=90,
    wedgeprops=dict(width=0.4)
)

plt.title("Cab Type Distribution")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 6.6 Customer Tenure - Histogram
# ------------------------------------------------------------

tenure = (
    df["Customer_Since_Months"]
    .dropna()
)

plt.figure(figsize=(9, 5))

plt.hist(
    tenure,
    bins=11,
    edgecolor="black"
)

plt.title(
    "Customer Tenure Distribution"
)

plt.xlabel(
    "Customer Since (Months)"
)

plt.ylabel(
    "Number of Customers / Trips"
)

plt.tight_layout()
plt.show()


# ============================================================
# 7. BIVARIATE ANALYSIS
# ============================================================

# ------------------------------------------------------------
# 7.1 Trip Distance vs Customer Rating
# ------------------------------------------------------------

scatter_data = df[
    [
        "Trip_Distance",
        "Customer_Rating"
    ]
].dropna()

# Sample 10,000 rows for faster plotting
if len(scatter_data) > 10000:

    scatter_data = scatter_data.sample(
        10000,
        random_state=42
    )

plt.figure(figsize=(9, 5))

plt.scatter(
    scatter_data["Trip_Distance"],
    scatter_data["Customer_Rating"],
    alpha=0.3
)

plt.title(
    "Trip Distance vs Customer Rating"
)

plt.xlabel("Trip Distance")
plt.ylabel("Customer Rating")

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 7.2 Cab Type vs Surge Category
# ------------------------------------------------------------

cab_target = pd.crosstab(
    df["Type_of_Cab"].fillna("Unknown"),
    df["__FeatEng_target__"]
)

cab_target.plot(
    kind="bar",
    stacked=True,
    figsize=(9, 5)
)

plt.title(
    "Cab Type vs Surge Pricing Category"
)

plt.xlabel("Cab Type")
plt.ylabel("Number of Trips")

plt.xticks(rotation=0)

plt.legend(
    title="Surge Category"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 7.3 Cancellation vs Surge Category
# ------------------------------------------------------------

groups = []

target_categories = sorted(
    df["__FeatEng_target__"]
    .dropna()
    .unique()
)

for category in target_categories:

    values = df.loc[
        df["__FeatEng_target__"] == category,
        "Cancellation_Last_1Month"
    ].dropna()

    groups.append(values)


plt.figure(figsize=(8, 5))

plt.boxplot(
    groups,
    labels=[
        f"Surge {x}"
        for x in target_categories
    ]
)

plt.title(
    "Cancellation Behavior Across Surge Categories"
)

plt.xlabel("Surge Category")
plt.ylabel(
    "Cancellations in Last Month"
)

plt.tight_layout()
plt.show()


# ------------------------------------------------------------
# 7.4 Gender vs Surge Category
# ------------------------------------------------------------

gender_target = pd.crosstab(
    df["Gender"].fillna("Unknown"),
    df["__FeatEng_target__"]
)

gender_target.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title(
    "Gender Distribution Across Surge Categories"
)

plt.xlabel("Gender")
plt.ylabel("Number of Trips")

plt.xticks(rotation=0)

plt.legend(
    title="Surge Category"
)

plt.tight_layout()
plt.show()


# ============================================================
# 8. CORRELATION ANALYSIS
# ============================================================

# Select only numerical columns
numeric_df = df.select_dtypes(
    include=np.number
)

# Remove target and index
numeric_features = numeric_df.drop(
    columns=[
        "__FeatEng_target__",
        "__index_level_0__"
    ],
    errors="ignore"
)

correlation = numeric_features.corr()


# ------------------------------------------------------------
# 8.1 Correlation Heatmap
# ------------------------------------------------------------

plt.figure(figsize=(10, 8))

plt.imshow(
    correlation,
    aspect="auto"
)

plt.colorbar(
    label="Correlation"
)

plt.xticks(
    range(len(correlation.columns)),
    correlation.columns,
    rotation=90
)

plt.yticks(
    range(len(correlation.columns)),
    correlation.columns
)

plt.title(
    "Numerical Feature Correlation Heatmap"
)

plt.tight_layout()
plt.show()


# ============================================================
# 9. FINAL EDA SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("FINAL EDA SUMMARY")
print("=" * 60)

print("\nDataset Shape:")
print(df.shape)

print("\nTotal Missing / Null Values:")
print(df.isnull().sum().sum())

print("\nColumns with Missing Values:")

final_missing = df.isnull().sum()

print(
    final_missing[
        final_missing > 0
    ].sort_values(
        ascending=False
    )
)

print("\nMissing Percentage:")

final_missing_percentage = (
    df.isnull().mean() * 100
)

print(
    final_missing_percentage[
        final_missing_percentage > 0
    ].sort_values(
        ascending=False
    )
)

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nSurge Category Distribution:")

print(
    df["__FeatEng_target__"]
    .value_counts()
    .sort_index()
)

print("\n" + "=" * 60)
print("EDA COMPLETED SUCCESSFULLY")
print("=" * 60)



"""## ***TASK***

## LOAD DATASET
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score, davies_bouldin_score

# Load dataset
df = pd.read_csv("/content/zipride_train.csv")

print("Dataset Shape:", df.shape)

df.head()

"""## FEATURE SELECTION"""

# Features selected for clustering

features = [
    "Trip_Distance",
    "Type_of_Cab",
    "Customer_Since_Months",
    "Destination_Type",
    "Customer_Rating",
    "Cancellation_Last_1Month"
]

X = df[features].copy()

print("Selected Features:")
print(X.columns.tolist())

print("\nShape:", X.shape)

"""## Check Missing Values"""

print("Missing Values:")
print(X.isnull().sum())

print("\nMissing Percentage:")
print(
    (X.isnull().mean() * 100).round(2)
)

"""## Separate Numerical and Categorical Features"""

numerical_features = [
    "Trip_Distance",
    "Customer_Since_Months",
    "Customer_Rating",
    "Cancellation_Last_1Month"
]

categorical_features = [
    "Type_of_Cab",
    "Destination_Type"
]

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

"""## Preprocessing"""

# Numerical preprocessing
numerical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ]
)


# Categorical preprocessing
categorical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="constant",
                                  fill_value="Unknown")),
        ("encoder", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ]
)


# Combine both
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_pipeline, numerical_features),
        ("cat", categorical_pipeline, categorical_features)
    ]
)

"""## Transform the Data"""

X_processed = preprocessor.fit_transform(X)

print("Original Shape :", X.shape)
print("Processed Shape:", X_processed.shape)

"""## Create a Sample for the 3 Models"""

np.random.seed(42)

sample_size = 10000

sample_indices = np.random.choice(
    X_processed.shape[0],
    size=sample_size,
    replace=False
)

X_sample = X_processed[sample_indices]

print("Sample Shape:", X_sample.shape)

"""## K-Means: Find Best Number of Clusters
We'll test K = 2 to 9.
"""

k_values = range(2, 10)

silhouette_scores = []

for k in k_values:

    kmeans = KMeans(
        n_clusters=k,
        random_state=42,
        n_init=10
    )

    labels = kmeans.fit_predict(X_sample)

    score = silhouette_score(
        X_sample,
        labels
    )

    silhouette_scores.append(score)

    print(
        "K =", k,
        "Silhouette Score =", round(score, 4)
    )

"""## Plot K-Means Results"""

plt.figure(figsize=(8, 5))

plt.plot(
    list(k_values),
    silhouette_scores,
    marker="o"
)

plt.xlabel("Number of Clusters (K)")
plt.ylabel("Silhouette Score")
plt.title("K-Means - Choosing Number of Clusters")

plt.grid(True)
plt.show()

"""### Apply K-Means"""

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

kmeans_labels = kmeans.fit_predict(
    X_sample
)

print("K-Means Clusters:")
print(
    np.unique(
        kmeans_labels,
        return_counts=True
    )
)

"""## Evaluate K-Means"""

kmeans_silhouette = silhouette_score(
    X_sample,
    kmeans_labels
)

kmeans_db = davies_bouldin_score(
    X_sample,
    kmeans_labels
)

print("K-Means Evaluation")
print("------------------")
print(
    "Silhouette Score:",
    round(kmeans_silhouette, 4)
)

print(
    "Davies-Bouldin Index:",
    round(kmeans_db, 4)
)

"""## Hierarchical Clustering"""

hierarchical = AgglomerativeClustering(
    n_clusters=3,
    linkage="ward"
)

hierarchical_labels = hierarchical.fit_predict(
    X_sample
)

print("Hierarchical Clusters:")
print(
    np.unique(
        hierarchical_labels,
        return_counts=True
    )
)

"""## Evaluate Hierarchical Clustering"""

hierarchical_silhouette = silhouette_score(
    X_sample,
    hierarchical_labels
)

hierarchical_db = davies_bouldin_score(
    X_sample,
    hierarchical_labels
)

print("Hierarchical Clustering Evaluation")
print("-----------------------------------")

print(
    "Silhouette Score:",
    round(hierarchical_silhouette, 4)
)

print(
    "Davies-Bouldin Index:",
    round(hierarchical_db, 4)
)

"""## DBSCAN"""

dbscan = DBSCAN(
    eps=0.8,
    min_samples=10
)

dbscan_labels = dbscan.fit_predict(
    X_sample
)

print("DBSCAN Labels:")
print(
    np.unique(
        dbscan_labels,
        return_counts=True
    )
)

"""### Evaluate DBSCAN"""

unique_labels = set(dbscan_labels)

# Remove noise
non_noise_mask = dbscan_labels != -1

dbscan_clean_labels = dbscan_labels[
    non_noise_mask
]

dbscan_clean_data = X_sample[
    non_noise_mask
]

number_of_clusters = len(
    set(dbscan_clean_labels)
)

print(
    "Number of DBSCAN Clusters:",
    number_of_clusters
)

print(
    "Noise Points:",
    np.sum(dbscan_labels == -1)
)

if number_of_clusters >= 2:

    dbscan_silhouette = silhouette_score(
        dbscan_clean_data,
        dbscan_clean_labels
    )

    dbscan_db = davies_bouldin_score(
        dbscan_clean_data,
        dbscan_clean_labels
    )

    print(
        "Silhouette Score:",
        round(dbscan_silhouette, 4)
    )

    print(
        "Davies-Bouldin Index:",
        round(dbscan_db, 4)
    )

else:

    print(
        "Not enough clusters for evaluation."
    )

"""## Compare the 3 Models"""

comparison = pd.DataFrame({
    "Model": [
        "K-Means",
        "Hierarchical",
        "DBSCAN"
    ],
    "Silhouette Score": [
        kmeans_silhouette,
        hierarchical_silhouette,
        dbscan_silhouette
        if number_of_clusters >= 2
        else np.nan
    ],
    "Davies-Bouldin Index": [
        kmeans_db,
        hierarchical_db,
        dbscan_db
        if number_of_clusters >= 2
        else np.nan
    ]
})

comparison

"""## See Cluster Sizes"""

print("K-Means Cluster Sizes:")
print(
    pd.Series(kmeans_labels)
    .value_counts()
    .sort_index()
)

print("\nHierarchical Cluster Sizes:")
print(
    pd.Series(hierarchical_labels)
    .value_counts()
    .sort_index()
)

print("\nDBSCAN Cluster Sizes:")
print(
    pd.Series(dbscan_labels)
    .value_counts()
    .sort_index()
)

"""## Create a Result DataFrame"""

sample_original = df.iloc[
    sample_indices
].copy()

sample_original["KMeans_Cluster"] = (
    kmeans_labels
)

sample_original["Hierarchical_Cluster"] = (
    hierarchical_labels
)

sample_original["DBSCAN_Cluster"] = (
    dbscan_labels
)

sample_original.head()

"""## Profile K-Means Clusters"""

kmeans_profile = sample_original.groupby(
    "KMeans_Cluster"
).agg({

    "Trip_Distance": "mean",

    "Customer_Since_Months": "mean",

    "Customer_Rating": "mean",

    "Cancellation_Last_1Month": "mean"

})

print(kmeans_profile)

"""## Check Cab Type Distribution"""

cab_distribution = pd.crosstab(
    sample_original["KMeans_Cluster"],
    sample_original["Type_of_Cab"],
    normalize="index"
) * 100

print(
    cab_distribution.round(2)
)

"""## Check Surge Distribution AFTER Clustering"""

surge_distribution = pd.crosstab(
    sample_original["KMeans_Cluster"],
    sample_original["__FeatEng_target__"],
    normalize="index"
) * 100

print(
    surge_distribution.round(2)
)

# ============================================================
# ZIPRIDE - XGBOOST HYPERPARAMETER TUNING
# ============================================================

# If XGBoost is not installed in Colab, uncomment this:
# !pip install -q xgboost


# ============================================================
# 1. IMPORT LIBRARIES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from xgboost import XGBClassifier

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 2. LOAD DATASET
# ============================================================

df = pd.read_csv("zipride_train.csv")

print("=" * 60)
print("DATASET INFORMATION")
print("=" * 60)

print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())


# ============================================================
# 3. SELECT FEATURES AND TARGET
# ============================================================

features = [
    "Trip_Distance",
    "Type_of_Cab",
    "Customer_Since_Months",
    "Destination_Type",
    "Customer_Rating",
    "Cancellation_Last_1Month"
]

target = "__FeatEng_target__"

X = df[features].copy()
y = df[target].copy()


# ============================================================
# 4. ENCODE TARGET
# ============================================================
# Original target:
# 1, 2, 3
#
# XGBoost multiclass classification expects:
# 0, 1, 2

y = y - 1

print("\nTarget Distribution:")
print(y.value_counts().sort_index())


# ============================================================
# 5. DEFINE NUMERICAL AND CATEGORICAL FEATURES
# ============================================================

numerical_features = [
    "Trip_Distance",
    "Customer_Since_Months",
    "Customer_Rating",
    "Cancellation_Last_1Month"
]

categorical_features = [
    "Type_of_Cab",
    "Destination_Type"
]


# ============================================================
# 6. PREPROCESSING
# ============================================================

numerical_pipeline = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="constant",
                fill_value="Unknown"
            )
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)


preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numerical_pipeline,
            numerical_features
        ),
        (
            "cat",
            categorical_pipeline,
            categorical_features
        )
    ]
)


# ============================================================
# 7. TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining Shape:", X_train.shape)
print("Testing Shape :", X_test.shape)


# ============================================================
# 8. BASELINE XGBOOST MODEL
# ============================================================

baseline_model = XGBClassifier(
    objective="multi:softprob",
    num_class=3,
    eval_metric="mlogloss",

    # BASELINE PARAMETERS
    n_estimators=100,
    max_depth=6,
    learning_rate=0.10,
    subsample=1.0,
    colsample_bytree=1.0,

    random_state=42,
    tree_method="hist"
)


# ============================================================
# 9. BASELINE PIPELINE
# ============================================================

baseline_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", baseline_model)
    ]
)


# ============================================================
# 10. TRAIN BASELINE MODEL
# ============================================================

print("\n" + "=" * 60)
print("TRAINING BASELINE XGBOOST")
print("=" * 60)

baseline_pipeline.fit(
    X_train,
    y_train
)


# ============================================================
# 11. BASELINE PREDICTION
# ============================================================

baseline_pred = baseline_pipeline.predict(X_test)

baseline_accuracy = accuracy_score(
    y_test,
    baseline_pred
)

print("\nBaseline Accuracy:",
      round(baseline_accuracy, 4))


# ============================================================
# 12. BASELINE PARAMETERS
# ============================================================

baseline_parameters = {
    "n_estimators": 100,
    "max_depth": 6,
    "learning_rate": 0.10,
    "subsample": 1.0,
    "colsample_bytree": 1.0
}

print("\nBaseline Parameters:")
for parameter, value in baseline_parameters.items():
    print(f"{parameter}: {value}")


# ============================================================
# 13. HYPERPARAMETER GRID
# ============================================================
#
# We will change these parameters:
#
# n_estimators
# max_depth
# learning_rate
# subsample
# colsample_bytree
#
# GridSearchCV will test different combinations.


param_grid = {

    "model__n_estimators": [
        100,
        200
    ],

    "model__max_depth": [
        3,
        5,
        7
    ],

    "model__learning_rate": [
        0.05,
        0.10
    ],

    "model__subsample": [
        0.8,
        1.0
    ],

    "model__colsample_bytree": [
        0.8,
        1.0
    ]
}


# ============================================================
# 14. XGBOOST MODEL FOR GRID SEARCH
# ============================================================

tuning_model = XGBClassifier(
    objective="multi:softprob",
    num_class=3,
    eval_metric="mlogloss",

    random_state=42,
    tree_method="hist"
)


# ============================================================
# 15. TUNING PIPELINE
# ============================================================

tuning_pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", tuning_model)
    ]
)


# ============================================================
# 16. GRID SEARCH
# ============================================================

print("\n" + "=" * 60)
print("STARTING HYPERPARAMETER TUNING")
print("=" * 60)

grid_search = GridSearchCV(

    estimator=tuning_pipeline,

    param_grid=param_grid,

    # 3-fold cross validation
    cv=3,

    # Optimize accuracy
    scoring="accuracy",

    # Use all CPU cores
    n_jobs=-1,

    verbose=1
)


grid_search.fit(
    X_train,
    y_train
)


# ============================================================
# 17. BEST PARAMETERS
# ============================================================

print("\n" + "=" * 60)
print("BEST PARAMETERS AFTER TUNING")
print("=" * 60)

best_parameters = grid_search.best_params_

for parameter, value in best_parameters.items():

    # Remove "model__" for cleaner display
    clean_parameter = parameter.replace(
        "model__",
        ""
    )

    print(
        f"{clean_parameter}: {value}"
    )


# ============================================================
# 18. BEST CROSS VALIDATION SCORE
# ============================================================

print(
    "\nBest Cross-Validation Accuracy:",
    round(
        grid_search.best_score_,
        4
    )
)


# ============================================================
# 19. BEST MODEL
# ============================================================

best_model = grid_search.best_estimator_


# ============================================================
# 20. TUNED MODEL PREDICTION
# ============================================================

tuned_pred = best_model.predict(
    X_test
)

tuned_accuracy = accuracy_score(
    y_test,
    tuned_pred
)

print(
    "\nTuned XGBoost Accuracy:",
    round(
        tuned_accuracy,
        4
    )
)


# ============================================================
# 21. PARAMETER CHANGE TABLE
# ============================================================

clean_best_parameters = {
    key.replace("model__", ""): value
    for key, value in best_parameters.items()
}

parameter_comparison = pd.DataFrame({

    "Parameter": [
        "n_estimators",
        "max_depth",
        "learning_rate",
        "subsample",
        "colsample_bytree"
    ],

    "Before Tuning": [

        baseline_parameters[
            "n_estimators"
        ],

        baseline_parameters[
            "max_depth"
        ],

        baseline_parameters[
            "learning_rate"
        ],

        baseline_parameters[
            "subsample"
        ],

        baseline_parameters[
            "colsample_bytree"
        ]
    ],

    "After Tuning": [

        clean_best_parameters[
            "n_estimators"
        ],

        clean_best_parameters[
            "max_depth"
        ],

        clean_best_parameters[
            "learning_rate"
        ],

        clean_best_parameters[
            "subsample"
        ],

        clean_best_parameters[
            "colsample_bytree"
        ]
    ]
})


print("\n" + "=" * 60)
print("PARAMETER CHANGES")
print("=" * 60)

print(
    parameter_comparison.to_string(
        index=False
    )
)


# ============================================================
# 22. ACCURACY COMPARISON
# ============================================================

accuracy_comparison = pd.DataFrame({

    "Model": [
        "Before Tuning",
        "After Tuning"
    ],

    "Accuracy": [
        baseline_accuracy,
        tuned_accuracy
    ]
})


print("\n" + "=" * 60)
print("ACCURACY COMPARISON")
print("=" * 60)

print(
    accuracy_comparison.to_string(
        index=False
    )
)


# ============================================================
# 23. ACCURACY IMPROVEMENT
# ============================================================

accuracy_improvement = (
    tuned_accuracy
    - baseline_accuracy
)

print(
    "\nAccuracy Improvement:",
    round(
        accuracy_improvement,
        4
    )
)

print(
    "Accuracy Improvement (%):",
    round(
        accuracy_improvement * 100,
        2
    ),
    "%"
)


# ============================================================
# 24. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 60)
print("TUNED XGBOOST CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        tuned_pred,
        target_names=[
            "Surge 1",
            "Surge 2",
            "Surge 3"
        ]
    )
)


# ============================================================
# 25. VISUALIZATION 1
# BASELINE VS TUNED ACCURACY
# ============================================================

plt.figure(
    figsize=(8, 5)
)

plt.bar(
    accuracy_comparison["Model"],
    accuracy_comparison["Accuracy"]
)

plt.ylabel(
    "Accuracy"
)

plt.xlabel(
    "Model"
)

plt.title(
    "XGBoost Accuracy Before and After Hyperparameter Tuning"
)

for i, value in enumerate(
    accuracy_comparison["Accuracy"]
):

    plt.text(
        i,
        value + 0.005,
        f"{value:.4f}",
        ha="center"
    )

plt.ylim(
    max(0, min(
        accuracy_comparison["Accuracy"]
    ) - 0.05),
    min(1.0, max(
        accuracy_comparison["Accuracy"]
    ) + 0.05)
)

plt.show()


# ============================================================
# 26. VISUALIZATION 2
# CONFUSION MATRIX
# ============================================================

cm = confusion_matrix(
    y_test,
    tuned_pred
)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Surge 1",
        "Surge 2",
        "Surge 3"
    ]
)

fig, ax = plt.subplots(
    figsize=(7, 6)
)

disp.plot(
    ax=ax,
    cmap="Blues"
)

plt.title(
    "XGBoost Confusion Matrix After Tuning"
)

plt.show()


# ============================================================
# 27. VISUALIZATION 3
# FEATURE IMPORTANCE
# ============================================================

xgb_model = (
    best_model
    .named_steps["model"]
)

fitted_preprocessor = (
    best_model
    .named_steps["preprocessor"]
)

feature_names = (
    fitted_preprocessor
    .get_feature_names_out()
)

feature_importances = (
    xgb_model.feature_importances_
)

feature_importance_df = pd.DataFrame({

    "Feature": feature_names,

    "Importance": feature_importances

})

feature_importance_df = (
    feature_importance_df
    .sort_values(
        "Importance",
        ascending=False
    )
)


# Top 15 features

top_features = (
    feature_importance_df
    .head(15)
)


plt.figure(
    figsize=(10, 7)
)

plt.barh(
    top_features["Feature"][::-1],
    top_features["Importance"][::-1]
)

plt.xlabel(
    "Importance"
)

plt.ylabel(
    "Feature"
)

plt.title(
    "Top XGBoost Feature Importances"
)

plt.show()


# ============================================================
# 28. VISUALIZATION 4
# EFFECT OF MAX DEPTH
# ============================================================

cv_results = pd.DataFrame(
    grid_search.cv_results_
)

depth_results = (
    cv_results
    .groupby(
        "param_model__max_depth"
    )["mean_test_score"]
    .mean()
)

plt.figure(
    figsize=(8, 5)
)

plt.plot(
    depth_results.index.astype(int),
    depth_results.values,
    marker="o"
)

plt.xlabel(
    "Max Depth"
)

plt.ylabel(
    "Mean Cross-Validation Accuracy"
)

plt.title(
    "Effect of Max Depth on XGBoost Performance"
)

plt.grid(True)

plt.show()


# ============================================================
# 29. VISUALIZATION 5
# EFFECT OF LEARNING RATE
# ============================================================

learning_rate_results = (
    cv_results
    .groupby(
        "param_model__learning_rate"
    )["mean_test_score"]
    .mean()
)

plt.figure(
    figsize=(8, 5)
)

plt.plot(
    learning_rate_results.index.astype(float),
    learning_rate_results.values,
    marker="o"
)

plt.xlabel(
    "Learning Rate"
)

plt.ylabel(
    "Mean Cross-Validation Accuracy"
)

plt.title(
    "Effect of Learning Rate on XGBoost Performance"
)

plt.grid(True)

plt.show()


# ============================================================
# 30. FINAL SUMMARY
# ============================================================

print("\n" + "=" * 60)
print("FINAL XGBOOST SUMMARY")
print("=" * 60)

print(
    "Baseline Accuracy:",
    round(baseline_accuracy, 4)
)

print(
    "Tuned Accuracy:",
    round(tuned_accuracy, 4)
)

print(
    "Improvement:",
    round(
        accuracy_improvement,
        4
    )
)

print("\nParameters Changed:")

for parameter in [
    "n_estimators",
    "max_depth",
    "learning_rate",
    "subsample",
    "colsample_bytree"
]:

    before = baseline_parameters[
        parameter
    ]

    after = clean_best_parameters[
        parameter
    ]

    print(
        f"{parameter}: "
        f"{before} → {after}"
    )

print("\nXGBoost Hyperparameter Tuning Completed.")

